# Generated by Django 4.2.24 on 2025-10-02 04:00

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_ciudad_customuser_foto_perfil_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='foto_perfil',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Sube una foto de perfil (opcional).', max_length=255, null=True, verbose_name='Foto de perfil'),
        ),
    ]
