# Generated by Django 4.2.24 on 2025-10-01 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_alter_mascota_foto_reaccion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mascota',
            old_name='edad',
            new_name='edad_meses',
        ),
    ]
