# Generated by Django 4.2.24 on 2025-10-02 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_rename_edad_mascota_edad_meses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='edad_meses',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
