# Generated by Django 4.2.24 on 2025-10-02 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0004_alter_mascota_edad_meses'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='sexo',
            field=models.CharField(choices=[('M', 'Macho'), ('H', 'Hembra')], default='M', max_length=1),
        ),
    ]
