# Generated by Django 4.2.24 on 2025-12-16 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0005_mascota_sexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
    ]
